apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "petestaks-ce05"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petestaks-ce05"
    spec:
      containers:
        - name: "petestaks-ce05"
          image: "tfgruy.azurecr.io/petestaks"
          ports:
          - containerPort: 8123