apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "petestaks-a04f"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petestaks-a04f"
    spec:
      containers:
        - name: "petestaks-a04f"
          image: "myfirstproject6456.azurecr.io/petestaks"
          ports:
          - containerPort: 8123