on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ajacr1.azurecr.io
        username: ${{ secrets.acr_ajacr1_username }}
        password: ${{ secrets.acr_ajacr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t ajacr1.azurecr.io/petestaks:${{ github.sha }}
        docker push ajacr1.azurecr.io/petestaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_petestaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep petestaks9820 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace petestaks9820`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: petestaks9820
        container-registry-url: ajacr1.azurecr.io
        container-registry-username: ${{ secrets.acr_ajacr1_username }}
        container-registry-password: ${{ secrets.acr_ajacr1_password }}
        secret-name: petestaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: petestaks9820
        manifests: |
          manifests/deployment-24.yml
          manifests/service-24.yml
        images: |
          ajacr1.azurecr.io/petestaks:${{ github.sha }}
        imagepullsecrets: |
          petestaksdockerauth